name: 'Julia test coverage report'
description: 'create and upload Julia test coverage report to Github pages'
author: 'YongHee Kim'

branding:
  icon: 'settings'
  color: 'gray-dark'

runs:
  using: 'composite'
  steps:
    - uses: julia-actions/julia-processcoverage@v1
    - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@4.6.4
        with:
            reports: 'lcov.info' 
            targetdir: 'coverage/dev' # REQUIRED # The directory where the generated report should be saved.
            historydir: '' 
            reporttypes: 'HtmlInline;Badges' # The output formats and scope (separated by semicolon) Values: Badges, Clover, Cobertura, CsvSummary, Html, HtmlChart, HtmlInline, HtmlInline_AzurePipelines, HtmlInline_AzurePipelines_Dark, HtmlSummary, JsonSummary, Latex, LatexSummary, lcov, MHtml, PngChart, SonarQube, TeamCitySummary, TextSummary, Xml, XmlSummary
            verbosity: 'Info' # The verbosity level of the log messages. Values: Verbose, Info, Warning, Error, Off
            tag: '${{ github.run_number }}_${{ github.run_id }}' # TODO. get commit id and Julia version     
    - name: Push Report
      uses: EndBug/add-and-commit@v4 # You can change this to use a specific version
      with:
        add: 'coverage/*'
        message: 'Coverage Report' # TODO: include Commit id
        ref: 'gh-pages' 
        remove: ''
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 